### ISSUE TITLE
Data refresh issue notification where there is no issue

### ISSUE THREAD

**Issue by rickydg** [tonesto7/echo-speaks#16] opened 2018-11-22 20:59 UTC
Currently running 1.3.0 on both app and Heroku on UK account. Was one of the users with the cookie expiration issue.

I now have it working consistently, but am still receiving notifications claiming the contrary!

**Comment by tmleafs** [comment] 2018-11-23 12:58
How have you managed to get it working consistently?

**Comment by tonesto7** [comment] 2018-11-30 14:13
This issue should be resolved in V2.0

**Comment by tonesto7** [comment] 2018-11-30 14:14
duplicate of #5

**Closed by tonesto7** 2018-11-30 14:14 UTC
Labels: bug, duplicate
